import {
  Receipt,
  Target,
  CreditCard,
  Activity,
  Sun,
  Calendar,
  Home,
  Coffee,
  ShoppingCart,
  Car,
  Bus,
  Train,
  Plane,
  Briefcase,
  Monitor,
  Smartphone,
  Wifi,
  Zap,
  Droplet,
  Flame,
  Gift,
  Heart,
  Music,
  Film,
  Gamepad2,
  Book,
  GraduationCap,
  Dumbbell,
  Utensils,
  Pizza,
  Shirt,
  Scissors,
  Baby,
  PawPrint,
  LucideIcon
} from 'lucide-react'

export const AVAILABLE_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: 'Receipt', icon: Receipt },
  { name: 'Target', icon: Target },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'Activity', icon: Activity },
  { name: 'Sun', icon: Sun },
  { name: 'Calendar', icon: Calendar },
  { name: 'Home', icon: Home },
  { name: 'Coffee', icon: Coffee },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Car', icon: Car },
  { name: 'Bus', icon: Bus },
  { name: 'Train', icon: Train },
  { name: 'Plane', icon: Plane },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Monitor', icon: Monitor },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Wifi', icon: Wifi },
  { name: 'Zap', icon: Zap },
  { name: 'Droplet', icon: Droplet },
  { name: 'Flame', icon: Flame },
  { name: 'Gift', icon: Gift },
  { name: 'Heart', icon: Heart },
  { name: 'Music', icon: Music },
  { name: 'Film', icon: Film },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Book', icon: Book },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'Utensils', icon: Utensils },
  { name: 'Pizza', icon: Pizza },
  { name: 'Shirt', icon: Shirt },
  { name: 'Scissors', icon: Scissors },
  { name: 'Baby', icon: Baby },
  { name: 'PawPrint', icon: PawPrint },
]

export const AVAILABLE_COLORS: string[] = [
  '#C5BFAE',
  '#C91111',
  '#39FF14',
  '#E36414',
  '#A3B18A',
  '#DDA15E',
  '#BC6C25',
  '#4A90E2',
  '#9B51E0',
  '#E5989B',
  '#B5838D',
  '#6D6875',
  '#2A9D8F',
  '#264653',
  '#E9C46A',
  '#F4A261',
  '#8AB17D',
  '#457B9D',
  '#1D3557',
  '#A8DADC',
  '#F1FAEE',
]
