import {
  Receipt, Target, CreditCard, Activity, Sun, Calendar, Home, Coffee,
  ShoppingCart, Car, Bus, Train, Plane, Briefcase, Monitor, Smartphone,
  Wifi, Zap, Droplet, Flame, Gift, Heart, Music, Film, Gamepad2, Book,
  GraduationCap, Dumbbell, Utensils, Pizza, Shirt, Scissors, Baby,
  PawPrint, Landmark, TrendingUp, Bitcoin,
  Camera, PenTool, Star, Umbrella, Trophy, Trees, Bike, Key,
  Lightbulb, Glasses, Headphones, Wrench, Hammer, Watch, Compass,
  Map, Globe, Cloud, Moon, Truck, Ship, Rocket, Crown, Coins,
  PiggyBank, Store, Anchor, Palette, LucideIcon
} from 'lucide-react'

export const AVAILABLE_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: 'Landmark', icon: Landmark },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'Bitcoin', icon: Bitcoin },
  { name: 'Receipt', icon: Receipt },
  { name: 'Target', icon: Target },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'Activity', icon: Activity },
  { name: 'Sun', icon: Sun },
  { name: 'Calendar', icon: Calendar },
  { name: 'Home', icon: Home },
  { name: 'Coffee', icon: Coffee },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Car', icon: Car },
  { name: 'Bus', icon: Bus },
  { name: 'Train', icon: Train },
  { name: 'Plane', icon: Plane },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Monitor', icon: Monitor },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Wifi', icon: Wifi },
  { name: 'Zap', icon: Zap },
  { name: 'Droplet', icon: Droplet },
  { name: 'Flame', icon: Flame },
  { name: 'Gift', icon: Gift },
  { name: 'Heart', icon: Heart },
  { name: 'Music', icon: Music },
  { name: 'Film', icon: Film },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Book', icon: Book },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'Utensils', icon: Utensils },
  { name: 'Pizza', icon: Pizza },
  { name: 'Shirt', icon: Shirt },
  { name: 'Scissors', icon: Scissors },
  { name: 'Baby', icon: Baby },
  { name: 'PawPrint', icon: PawPrint },
  { name: 'Camera', icon: Camera },
  { name: 'PenTool', icon: PenTool },
  { name: 'Star', icon: Star },
  { name: 'Umbrella', icon: Umbrella },
  { name: 'Trophy', icon: Trophy },
  { name: 'Trees', icon: Trees },
  { name: 'Bike', icon: Bike },
  { name: 'Key', icon: Key },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Glasses', icon: Glasses },
  { name: 'Headphones', icon: Headphones },
  { name: 'Wrench', icon: Wrench },
  { name: 'Hammer', icon: Hammer },
  { name: 'Watch', icon: Watch },
  { name: 'Compass', icon: Compass },
  { name: 'Map', icon: Map },
  { name: 'Globe', icon: Globe },
  { name: 'Cloud', icon: Cloud },
  { name: 'Moon', icon: Moon },
  { name: 'Truck', icon: Truck },
  { name: 'Ship', icon: Ship },
  { name: 'Rocket', icon: Rocket },
  { name: 'Crown', icon: Crown },
  { name: 'Coins', icon: Coins },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'Store', icon: Store },
  { name: 'Anchor', icon: Anchor },
  { name: 'Palette', icon: Palette },
]

export const AVAILABLE_COLORS: string[] = [
  '#C5BFAE', '#C91111', '#39FF14', '#E36414', '#A3B18A',
  '#DDA15E', '#BC6C25', '#4A90E2', '#9B51E0', '#E5989B',
  '#B5838D', '#6D6875', '#2A9D8F', '#264653', '#E9C46A',
  '#F4A261', '#8AB17D', '#457B9D', '#1D3557', '#A8DADC',
  '#F1FAEE',
  
  // New vibrant colors
  '#FF007F', '#FF3366', '#FF9933', '#FFD700', '#33CC33',
  '#00FFCC', '#3399FF', '#9933FF', '#CC00FF', '#FF00CC',
  
  // Pastel tones
  '#FFB6C1', '#FFDAB9', '#E6E6FA', '#E0FFFF', '#F0FFF0',
  '#FFF0F5', '#FFE4E1', '#F5DEB3', '#D3D3D3', '#F0E68C',
  
  // Dark/Muted earthy tones
  '#2F4F4F', '#8B4513', '#556B2F', '#483D8B', '#800000',
  '#008080', '#000080', '#696969', '#A0522D', '#2E8B57',
]
